version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "forum"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "forum"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://admin:root@db:5432/forum
    depends_on:
      db:
        condition: service_healthy

  # smtp:
  #   image: namshi/smtp
  #   container_name: smtp
  #   ports:
  #     - "25:25"
  #   environment:
  #     - RELAY_NETWORKS=:192.168.0.0/24
  #   restart: unless-stopped

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
        - ./data:/data
    ports:
        - 8025:8025
        - 1025:1025
    environment:
        MP_MAX_MESSAGES: 5000
        MP_DATABASE: /data/mailpit.db
        MP_SMTP_AUTH_ACCEPT_ANY: 1
        MP_SMTP_AUTH_ALLOW_INSECURE: 1

  # postfix:
  #   image: boky/postfix:latest
  #   container_name: postfix
  #   hostname: ${POSTFIX_HOSTNAME}
  #   environment:
  #     - ALLOWED_SENDER_DOMAINS=${ALLOWED_SENDER_DOMAINS}
  #     - POSTFIX_mynetworks=${POSTFIX_MYNETWORKS}
  #     - POSTFIX_smtpd_tls_cert_file=/etc/ssl/postfix/fullchain.pem
  #     - POSTFIX_smtpd_tls_key_file=/etc/ssl/postfix/privkey.pem
  #   ports:
  #     - "25:25"
  #     - "587:587"
  #   volumes:
  #     - ./postfix-data:/var/spool/postfix
  #     - ./certs:/etc/ssl/postfix:ro
  #   restart: unless-stopped

volumes:
  pgdata: